server:
  port: 8085

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://payment-db:5432/payment_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.n11.paymentservice: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true

iyzico:
  api-key: ${IYZICO_API_KEY}
  secret-key: ${IYZICO_SECRET_KEY}
  base-url: https://sandbox-api.iyzipay.com