server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**

            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/products/**

            - id: cart-service
              uri: lb://CART-SERVICE
              predicates:
                - Path=/api/cart/**

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/orders/**

            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.n11.apigateway: DEBUG